### ISSUE TITLE
Mapster.tool fails on types derived from external types

### ISSUE THREAD

**Issue by byte3** [MapsterMapper/Mapster#319] opened 2021-03-10 12:05 UTC
I have found a possible bug when using mapster.tool with derived types, when the base class is located in a nuget package.
I am using mapster.tool version 8.0.1

mapster.tool fails with this exception:
> Cannot find library: Microsoft.Azure.Cosmos.Client
> Unhandled exception. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
> Could not load file or assembly 'Microsoft.Azure.Cosmos.Client, Version=3.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
> at system.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
> at System.Reflection.RuntimeModule.GetTypes()
> at System.Reflection.Assembly.GetTypes()
> at Mapster.Tool.Extensions.Scan(CodeGenerationConfig config, Assembly assembly) in D:\git\Mapster\src\Mapster.Tool\Extensions.cs:line 177
> at Mapster.Tool.Program.GenerateModels(ModelOptions opt) in D:\git\Mapster\src\Mapster.Tool\Program.cs:line 123
> at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult\`1 result, Action\`1 action)
> at Mapster.Tool.Program.Main(String[] args) in D:\git\Mapster\src\Mapster.Tool\Program.cs:line 17
> System.IO.FileNotFoundException: Could not load file or assembly
> 'Microsoft.Azure.Cosmos.Client, Version=3.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
> File name: 'Microsoft.Azure.Cosmos.Client, Version=3.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

Here's the minimal code to reproduce the issue:

program.cs
```csharp
using Microsoft.Azure.Cosmos;
using System;

namespace MapsterTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }

    public class ApplicationDbClient : CosmosClient
    {
        public ApplicationDbClient() : base("ConnectionString")
        { }
    }
}
```

csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.1.5" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.17.0" />
  </ItemGroup>

  <Target Name="Mapster" AfterTargets="AfterBuild">
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet tool restore" />
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet mapster model -a &quot;$(TargetDir)$(ProjectName).dll&quot;" />
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet mapster extension -a &quot;$(TargetDir)$(ProjectName).dll&quot;" />
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet mapster mapper -a &quot;$(TargetDir)$(ProjectName).dll&quot;" />
  </Target>

  <ItemGroup>
    <Generated Include="**\*.g.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>
  <Target Name="CleanGenerated">
    <Delete Files="@(Generated)" />
  </Target>

</Project>
```

fyi: I also posted this issue a some days ago over on [stackoverflow](https://stackoverflow.com/questions/66409492/mapster-tool-fails-generating-mapper), but got no answers.

**Comment by neozhu** [comment] 2021-04-02 14:06
me too.

**Comment by neozhu** [comment] 2021-04-06 13:12
first
#skip this step if you already have dotnet-tools.json
dotnet new tool-manifest 

dotnet tool install Mapster.Tool

then
```<Target Name="Mapster">
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet build" />
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet tool restore" />
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet mapster model -a &quot;$(TargetDir)$(ProjectName).dll&quot;" />
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet mapster extension -a &quot;$(TargetDir)$(ProjectName).dll&quot;" />
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet mapster mapper -a &quot;$(TargetDir)$(ProjectName).dll&quot;" />
  </Target>

then 
run
dotnet msbuild -t:Mapster

**Comment by WeLikeAich** [comment] 2021-04-12 02:40
@chaowlert Could you provide some context as to why this issue was closed? Was it closed as a Won't Fix, Not Reproducible, etc? I am having this issue as well and is so far the single point of me not being able to use Mapster in my project.

Thanks!

**Comment by WeLikeAich** [comment] 2021-04-12 03:21
@chaowlert Using the new Mapster.Tool 8.2.0 and Mapster 7.2.0, I am still able to reproduce this same issue. I have created a project containing the minimal steps to reproduce [here](https://github.com/WeLikeAich/MapsterTest). It includes 4 projects, a rest-startup project that does not deal with Mapster, a "Service" project which is where I am trying to use the Code-Generation, and two projects, one with an external inheritance and one without. The one with an external Inheritance fails even when that class is not being mapped, the one without an external reference succeeds on build.

`3>Tool 'mapster.tool' (version '8.2.0') was restored. Available commands: dotnet-mapster
3>
3>Restore was successful.
3>Unhandled exception. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
3>Could not load file or assembly 'Microsoft.AspNetCore.Identity.EntityFrameworkCore, Version=5.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Invalid pointer (0x80004003 (E_POINTER))
3>   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
3>   at System.Reflection.RuntimeModule.GetTypes()
3>   at System.Reflection.Assembly.GetTypes()
3>   at Mapster.Tool.Extensions.Scan(CodeGenerationConfig config, Assembly assembly) in D:\git\Mapster\src\Mapster.Tool\Extensions.cs:line 177
3>   at Mapster.Tool.Program.GenerateModels(ModelOptions opt) in D:\git\Mapster\src\Mapster.Tool\Program.cs:line 146
3>   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
3>   at Mapster.Tool.Program.Main(String[] args) in D:\git\Mapster\src\Mapster.Tool\Program.cs:line 17
3>System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.Identity.EntityFrameworkCore, Version=5.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Invalid pointer (0x80004003 (E_POINTER))
3>File name: 'Microsoft.AspNetCore.Identity.EntityFrameworkCore, Version=5.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'`

**Comment by chaowlert** [comment] 2021-04-12 16:18
@WeLikeAich  I just checked, it is because you add Mapster target inside Service project, in fact it should be inside HasExternalTypeLibrary. Please stick to this setup. (Yours one, ProjectName has been modified)

```xml
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet mapster model -a &quot;$(TargetDir)$(ProjectName).dll&quot;" />
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet mapster extension -a &quot;$(TargetDir)$(ProjectName).dll&quot;" />
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet mapster mapper -a &quot;$(TargetDir)$(ProjectName).dll&quot;" />
```

If you would like to include types from other projects, pls use [`ICodeGenerationRegister`](https://github.com/MapsterMapper/Mapster/wiki/Fluent-API-Code-generation)

**Closed by chaowlert** 2021-04-12 16:18 UTC

**Comment by WeLikeAich** [comment] 2021-04-12 23:33
@chaowlert Thanks for the response, was able to finally get my test project working. I will update the test repo posted above with the working solution which can be used as a sample project if you would like.

**Comment by sevenver12** [comment] 2021-07-07 13:02
Is there a way to also make the ICodeGenerationRegister notice in which dlls can the [Mapper] interfaces be found?
