### ISSUE TITLE
HasConversion

### ISSUE THREAD

**Issue by sonsy-soft** [MapsterMapper/Mapster#273] opened 2020-10-15 05:55 UTC
ProjectToType dose not detect if property in ef core has HasConversion in propertybuilder at EntityTypeBuilder.

please try it

**Comment by chaowlert** [comment] 2020-10-15 14:20
I had production code with HasConversion and using ProjectToType. Pls help provide reproducible code to inspect.

**Comment by sonsy-soft** [comment] 2020-10-23 16:55
```

public class EncryptConverter : ValueConverter<string, string>
    {
        public EncryptConverter(ConverterMappingHints mappingHints = default)
            : base(EncryptExpr, DecryptExpr, mappingHints)
        { }

        static Expression<Func<string, string>> DecryptExpr = x => new string(x.Trim().Decrypt());
        static Expression<Func<string, string>> EncryptExpr = x => new string(x.Trim().Encrypt());
    }

public void Configure(EntityTypeBuilder<Payments> builder)
        {
            builder
                .Property               (x => x.Username)
                .HasConversion          (new EncryptConverter());
        }
```

**Comment by chaowlert** [comment] 2020-10-24 00:16
I just tested ProjectToType with include HasConversion for encrypt/decrypt. I already ensure db field is encrypted. And I can ProjectToType to dto with plain text just fine. (tested with EF Core 3.1.7)

I believe problem is somewhere else, and it could belong to EF. Since HasConversion doesn't the issue, it will close this issue until we found new evident.

**Closed by chaowlert** 2020-10-24 00:16 UTC
Labels: waiting for info
