### ISSUE TITLE
Mapping Dictionary is changing Key Case

### ISSUE THREAD

**Issue by OFark** [MapsterMapper/Mapster#474] opened 2022-09-08 10:28 UTC
If I map a dictionary with string keys to another, and I have the `TypeAdapterConfig.GlobalSettings.Default.NameMatchingStrategy(NameMatchingStrategy.Flexible);` setting, it's converting the dictionary keys to Title case.
I can stop is doing this by using: `NameMatchingStrategy.Exact` setting instead.

I find this behaviour odd, It's not matching properties, when it's mapping dictionary keys, so why swap the case around in the first place?

**Comment by andrerav** [comment] 2023-01-09 21:38
Probably some kind of duplicate of #388

**Comment by andrerav** [comment] 2023-05-29 21:09
Fixed in #590

**Closed by andrerav** 2023-05-29 21:09 UTC
